### ISSUE TITLE
[Doc] Update README file with the contributors list.

### ISSUE THREAD

**Issue by jayesh-srivastava** [kaiwalyakoparkar/classroom-monitor-bot#37] opened 2021-07-26 18:22 UTC
We need to add a 'Contributors List' section in the README file where the names of all the current contributors should be displayed. The names should be a link that will direct any user to the contributor's GitHub profile.

**Comment by VarunSAthreya** [comment] 2021-07-26 21:13
We can use [this](https://contrib.rocks/preview) website directly to generate dynamic contributor's list.

**Comment by kaiwalyakoparkar** [comment] 2021-07-28 17:44
@jayesh-srivastava A issue is already present regarding this #35 . This is a duplicate of current issue so sadly I will have to close it. Please check through opened/closed issue before raising an issue. The current problems
- The first issues #35 is already assigned
- @VarunSAthreya made a PR based on this issue
- The assigned member is not aware of this

Possible solution:
- I will follow up with assigned member and ask them if they have started working on this. If yes then I will have to close the PR as well. Because that won't be a good open source spirit.
- If not then I will ask them if they have any problem transferring the issue assignment and then would have to make it work that way. 

Hope you understand and take my suggestion into notice for further contributions

**Comment by kaiwalyakoparkar** [comment] 2021-07-29 11:51
@jayesh-srivastava As that being said. The earlier assignee has raised a PR so I am closing this issue and the related PR made corresponding to this issue. Hope you understand :slightly_smiling_face:

**Closed** 2021-07-29 11:52 UTC
Labels: duplicate, good first issue, 🚧 status: blocked
